"""followers

Revision ID: 12df26949c23
Revises: 9a688dd3d47e
Create Date: 2019-04-15 12:21:38.173345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12df26949c23'
down_revision = '9a688dd3d47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
